Update script to tag all five release repos
git-svn-id: https://repo.socialtext.net:8999/svn/stconfig/trunk@556 c8a2641f-bf1a-0410-9bac-bc2d7d3cadf3

diff --git a/stbin/tag-release b/stbin/tag-release
--- a/stbin/tag-release
+++ b/stbin/tag-release
@@ -1,11 +1,15 @@
 #!/bin/sh
 set -e
 
+DRY_RUN=""
+VERBOSE=""
+
 BRANCH=$1
 KIND=${2:-"release"}
-MSG=$3
+MSG=${3:-""}
+
 if [ -z "$BRANCH" ]; then
-    echo "Usage: $0 branch [type] [message] [version]"
+    echo "Usage: $0 branch [prefix [message [version]]]"
     exit 1
 fi
 
@@ -16,10 +20,30 @@ if [ -z "$VERSION" ]; then
 fi
 
 TAG=`get-next-release-tag $KIND $VERSION`
-MESSAGE="Copying /socialtext/branches/$BRANCH to /socialtext/tags/$TAG. $MSG"
-BRANCH_URL=$(st-branch-url $BRANCH)
-TAG_URL="$ST_CODE_REPO/tags/$TAG"
-
-if svn -q copy -m "$MESSAGE" $BRANCH_URL $TAG_URL >/dev/null; then
-    echo "Created tag $TAG from branch $BRANCH"
+if [ -z "$TAG" ]; then
+    echo "Error: Could not determine next $KIND tag for $BRANCH";
+    exit 1;
 fi
+
+for REPO in  {socialtext,socialtext-skins,socialtext-reports,control,appliance} ;
+
+do
+    
+    MESSAGE="Copying /$REPO/branches/$BRANCH to /$REPO/tags/$TAG $MSG"
+    BRANCH_URL="$ST_SVN/$REPO/branches/$BRANCH"
+    TAG_URL="$ST_SVN/$REPO/tags/$TAG"
+   
+    if [ $VERBOSE ]; then
+        echo Message: $MESSAGE
+        echo From: $BRANCH_URL
+        echo To: $TAG_URL
+    fi
+
+    if [ ! $DRY_RUN  ]; then 
+        if svn -q copy -m "$MESSAGE" $BRANCH_URL $TAG_URL >/dev/null; then
+            echo "Created $REPO tag $TAG from branch $BRANCH"
+        fi
+    fi
+
+done
+
